#!/bin/bash -ex

NODEUSER=node

REPO="joeferner/redis-commander"
VERSION=$(gh_releases $REPO | sort -V | tail -1)
URL="git+https://github.com/$REPO.git"

su -lc "[[ "$FAB_HTTP_PROXY" ]] && export http_proxy=$FAB_HTTP_PROXY; cd /opt/tklweb-cp && npm i $URL#$VERSION" $NODEUSER
su -lc "[[ "$FAB_HTTP_PROXY" ]] && export http_proxy=$FAB_HTTP_PROXY; cd /opt/tklweb-cp && pm2 start ecosystem.config.js && sleep 20 && pm2 save && pm2 kill" $NODEUSER

echo {} > /opt/tklweb-cp/node_modules/redis-commander/config/local-production.json

rm /etc/nginx/sites-enabled/tkl-default
ln -s /etc/nginx/sites-available/valkey /etc/nginx/sites-enabled/valkey
