#!/bin/bash -ex

NODEUSER=node
NODEAPP=/opt/tklweb-cp

grep -qxF 'cafile=/etc/ssl/certs/ca-certificates.crt' /home/$NODEUSER/.npmrc || \
    echo 'cafile=/etc/ssl/certs/ca-certificates.crt' >> /home/$NODEUSER/.npmrc
chown $NODEUSER:$NODEUSER /home/$NODEUSER/.npmrc

VERSION=$(su -lc "npm view redis-commander version" $NODEUSER)
su -lc "[[ -n \"$FAB_HTTP_PROXY\" ]] && export http_proxy=\"$FAB_HTTP_PROXY\"; cd $NODEAPP && npm install --save-exact redis-commander@$VERSION" $NODEUSER
su -lc "cd $NODEAPP && pm2 start ecosystem.config.js && sleep 20 && pm2 save && pm2 kill" $NODEUSER

echo {} > $NODEAPP/node_modules/redis-commander/config/local-production.json

rm /etc/nginx/sites-enabled/tkl-default
ln -s /etc/nginx/sites-available/valkey /etc/nginx/sites-enabled/valkey

rm -f /usr/local/bin/{n,node,npm,npx,corepack}
rm -rf /usr/local/n \
       /usr/local/src/n \
       /usr/local/include/node \
       /usr/local/lib/node_modules/npm \
       /usr/local/lib/node_modules/corepack \
       /usr/local/share/doc/node \
       /usr/local/share/man/man1/node.1
rm -f /usr/local/etc/npmrc

hash -r
dpkg-query -S "$(readlink -f "$(command -v node)")" | grep -q '^nodejs:'
dpkg-query -S "$(readlink -f "$(command -v npm)")" | grep -q '^npm:'

rm -rf /tmp/npm*
