#!/bin/bash -e
# regenerate valkey password & disable protected mode by default

. /etc/default/inithooks

PASS=""
while [ -z "$PASS" ]; do
    PASS=$(openssl rand 90 | openssl base64 -A) || true
done

sed -i "s|protected-mode yes|protected-mode no|" /etc/valkey/valkey.conf
sed -ri "s|(# *)?requirepass .*|requirepass $PASS|" /etc/valkey/valkey.conf
sed -ri "s|--redis-password='.*'|--redis-password='$PASS'|" /opt/tklweb-cp/ecosystem.config.js
